config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :publishers
  resources :books
  resources :users, only: [:create,:show,:new,:index]
  resources :sessions, only: [:create,:new,:destroy]
  post '/signin', to: 'sessions#create', as: 'signin'
  root to: 'authors#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
    validates :first_name, :last_name, presence: true
    has_many :publications
    has_many :books,through: :publications
    def full_name
        "#{first_name } #{last_name}"
    end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications
  has_many :authors, through: :publications

  validates :title, presence: true
  validates :idsn, presence: true
  validates :page_count, presence: true
  validates :price, presence: true
  validates :publisher_id, presence: true
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  validates_presence_of :name
  validates_length_of :name, minimum: 5
  validates_length_of :name, maximum: 40
  validates_uniqueness_of :name,  case_sensitive: false
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  before_action :set_user, only: [:show, :edit,:update,:destroy]
  
  
  def index
    
  end
  
  def show
  end
  
  def new
    @author = Author.new
  end
  
  def create
    
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = 'Saved!'
      redirect_to @author
    else
      flash[:error] = 'Sorry, no created'
      redirect_to new_author_path
    end
  end
  
  def edit

    if(@author)
      render :edit
    else
      flash[:error] = 'author not found'
      redirect_to authors_path
    end
    
  end
  
  def update

    if @author.update author_params
      flash[:success] = 'Author updated'
      redirect_to @author
    else
      flash[:error] = 'Invalid data'
      redirect_to authors_path
    end
    
  end
  
  def destroy
    flash[:success] = 'Deleted!'
    @author.destroy
    redirect_to authors_path
  end
  
  private
  
  def author_params
    params.require(:author).permit(:first_name,:last_name)
  end
  
  def set_user
    @author = Author.find(params[:id])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book, except: [:index, :new, :create]
def index
@books = Book.all
end
def show
end
def new

@book = Book.new
@publishers = Publisher.all
@authors = Author.all

end
def create
@book = Book.new(book_params)
if @book.save
flash[:success] = 'Book has been created'
redirect_to @book
else
    
flash.now[:danger] = 'Book has not been created'
render :new
end
end
def edit
end
def update
if @book.update(book_params)
flash[:success] = 'Book has been updated'
redirect_to @book
else
flash[:danger] = 'Book has not been updated'
render :edit
end
end
def destroy
if @book.destroy
flash[:success] = 'Book has been deleted'
redirect_to books_path
end
end
private
def book_params
params.require(:book).permit(:title, :idsn, :page_count, :price, :description,
:published_at, :publisher_id)
end
def set_book
@book = Book.find(params[:id])
end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  
  
  before_action :set_publisher, only: [:show, :edit, :update,:destroy]
  
  def index
    @publishers = Publisher.all
  end
  
  def show
    
  end
  
  def new
    
  end
  
  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:success] = 'Salvado!'
      redirect_to publisher_path(@publisher)
    else
      flash[:error] = 'Dont created!'
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    @publisher.update(publisher_params)
    redirect_to @publisher
  end
  
  def destroy
    @publisher.destroy
    redirect_to publishers_path()
  end
  
  private
  
  def publisher_params
    params.require(:publisher).permit(:name)
  end
  
  def set_publisher
    @publisher = Publisher.find(params[:id])
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

    redirect_to root_url if current_user
    
  end
  
  def create
    @user = User.find_by(email: params[:email])
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Loged In"
      redirect_to root_path
    else
      flash[:danger] = "Not loged in"
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path
  end
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user,only: [:show]
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_attributes)
    
    if @user.save
      flash[:success] = "User Created"
      redirect_to @user
    else
      flash[:danger] = "User not created"
      #require "pry";binding.pry
      render :new
    end
  end
  
  private 
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_attributes
    params.require(:user).permit(:first_name,:last_name,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
 Index Page
 <%= "Loged In" %>
 <%= link_to "Books", books_path %>
 <%= link_to 'Create new author',new_author_path %>
 <%= link_to 'Sign Up', new_user_path %>
 <%= link_to "Users", users_path %>
 <%= link_to "Sign in", new_session_path %>

app/views/authors/new.html.erb
<%= flash[:error] %>

<%= form_for @author do |f|%>

<%= f.text_field :first_name %>

<%= f.text_field :last_name %>

<%= f.submit %>

<% end %>

app/views/authors/show.html.erb
<%= flash[:success] %>

<%= flash[:error] %>

app/views/books/index.html.erb
<%= link_to "Create book", new_book_path %>

app/views/books/new.html.erb
<%= flash[:danger] %>

<%= form_for @book do |f| %>

<%= f.text_field :title %>
<%= f.text_field :idsn %>
<%= f.text_field :page_count %>
<%= f.text_field :price %>
<%=  f.select :publisher_id, 
              @publishers.map{|f|[f.name,f.id]},
              prompt: 'Select publisher' %>
              
<%= f.collection_check_boxes :author_ids, 
                              @authors, 
                              :id , 
                              :full_name,
                              {label: false,
                              class: "xyz123"} %>

<%= f.file_field :name %>

<%= f.submit "Create Book" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>


</body>
</html>

app/views/shared/_footer.html.erb
<h1>footer</h1>

app/views/shared/_header.html.erb
header

app/views/users/new.html.erb
<%= flash[:danger] %>

<%= form_for @user do |f| %>
  
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
  
<% end %>

app/views/users/show.html.erb
<%= flash[:success] %>

// show.html.erb
<section>
<div class='col-sm-10 col-sm-offset-1'>
<header>
<h3 class='titles'><%= "#{@user.full_name}" %>'s Profile</h3>
</header>
<p id="first-name">First name: <%= @user.first_name %></p>
<p id="last-name">Last name: <%= @user.last_name %></p>
<p id="email">Email: <%= @user.email %></p>
</div>
</section>